### ISSUE TITLE
Add biber support

### ISSUE THREAD

**Issue by Boltzmann** [csabasulyok/gradle-latex#23]
[Biber](https://sourceforge.net/projects/biblatex-biber/?source=typ_redirect) is sometimes easier to handle (found only german sources, e.g. [here](http://texwelt.de/wissen/fragen/5398/was-sind-die-vorteile-von-biber-gegenuber-bibtex)) than bibtex itself. 

I imagine a `build.gradle` with something like
`tex(tex: 'document.tex', biber: 'references', pdf: 'output.pdf')`
and then the document is processed with biber instead of bibtex.

**Comment by csabasulyok** [comment]
- Support added in [this commit](https://github.com/csabasulyok/gradle-latex/commit/8de43e0236de4e0a2c55aaa735fd3c4ccbdc97af).
- It will be available in version 2.0, until then a snapshot can be built from the current repository.
- An example is added [here](https://github.com/csabasulyok/gradle-latex/tree/2.0-SNAPSHOT/examples/2-withbib)
- The actual syntax in `build.gradle` is now:
`tex(tex: 'document.tex', bib: 'references.bib', bibCommand: 'biber', pdf: 'output.pdf')`

@Boltzmann thanks for the idea, let me know if it works out for you.

**Comment by Boltzmann** [comment]
Nice. It works out for me ... and is smoother than my own hacks.
