### ISSUE TITLE
Add xelatex support

### ISSUE THREAD

**Issue by bodand** [csabasulyok/gradle-latex#31]
The title says it all.

**Comment by csabasulyok** [comment]
- support added
- it will be available in version 2.0, until then a snapshot can be built from the current repository
- example [here](https://github.com/csabasulyok/gradle-latex/tree/2.0-SNAPSHOT/examples/8-withxelatex)
- syntax: `...   tex(tex: 'document.tex', pdfCommand: 'xelatex')   ...`
